### ISSUE TITLE
можете помочь со сбер лампой е14

### ISSUE THREAD

**Issue by Omantik** [Brokly/ESPHOME_SBER_SBDV-00115#2]
Добрый день
лампа от сбера е14 похоже сейчас пошли тоже на новом чипе и с измененным загрузчиком
маркировка sbdv-00117
чип CBLC9 (BK7231N ), в ранних был WBLC9 (BK7231T)
на чистой прошивке под BK7231N  не запускается. попробовал ту что была для SBDV-00115 - тоже нет запуска. вернул считанный бэкап - запустилась
[readResult_BK7231N_QIO_2343_2024-28-1-10-44-05 sber e14.zip](https://github.com/Brokly/ESPHOME_SBER_SBDV-00115/files/14075402/readResult_BK7231N_QIO_2343_2024-28-1-10-44-05.sber.e14.zip)

**Comment by Brokly** [comment]
Попробуйте ее по методике описанной в текущем репозитарии.   Если получится прошить удачно и она появится как узел еспхоум, то просто нужно поправить конфиг. Если же не получится, то значит сбер в очередной раз сменил ключи шифрования и тут я бессилен.

**Comment by Omantik** [comment]
Прошивку от е27 лампы я пробовал - не запустилась(((

**Comment by Zotio** [comment]
Присоединяюсь к листу ожидания. Первый день как прикоснулся к beken.  На 115200 шить не захотелась, на 921600 CRC error.

**Comment by Brokly** [comment]
> Omantik
Опишите подробнее,  что значит "не запустилась" ? Вы получили ошибку о невозможности прошить ? Или какие то другие симптомы?


> Присоединяюсь к листу ожидания. Первый день как прикоснулся к beken. На 115200 шить не захотелась, на 921600 CRC error.
Не очень понятно какой именно помощи вы ждете от меня ? Опишите/покажите что именно и как вы делаете.

**Comment by Omantik** [comment]
> > Omantik
> > Опишите подробнее,  что значит "не запустилась" ? Вы получили ошибку о невозможности прошить ? Или какие то другие симптомы?
прошивка заливается без проблем. после подачи питания точка доступа не появляется

**Comment by Zotio** [comment]
> Не очень понятно какой именно помощи вы ждете от меня ? 

 Никакой. Просто решил поделиться... Но если вы готовы помочь ответьте на вопрос можно ли прошить другой загрузчик по spi?  Или он не первый в цепи загрузки ?

>  CRC error

прошивка кстати прошла успешно, мой косяк с проводами.

**Comment by Brokly** [comment]
Я бы посоветовал вам обратиться к https://github.com/esnet146 , он в этом вопросе больше поможет вам. Сам я не использовал прошивку по SPI этих процессоров, просто не было необходимости.

**Comment by Brokly** [comment]
> > > Omantik
>>> после подачи питания точка доступа не появляется

Могу только посоветовать залить вашу прошивку по UART, причем прошивка должна иметь те же ключи шифрования, что указаны в руководстве.

**Comment by NonPIayerCharacter** [comment]
E14 config
```
esphome:
  name: sber-bulb
  friendly_name: sber_bulb
  platformio_options:
    board_build.bkcrypt_coeffs: 7d1ff9b3e3ffefde5d93b57eefefeb8b
    board_build.bkota.key: 908f771bac2ff1aa619b897c14c5a88b
    board_build.bkota.iv: 1e647fab598d727c
    board_flash.download: "0x132000+0xAE000"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "--"

ota:
  password: "--"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  domain: .lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sber-Bulb Fallback Hotspot"
    password: "--"


sensor:
  - platform: wifi_signal
    name: WiFi Signal Sensor
    update_interval: 60s

switch:
  - platform: restart
    name: Restart

bp1658cj:
  data_pin: P26
  clock_pin: P24
  max_power_color_channels: 3
  max_power_white_channels: 3

output:
  - platform: bp1658cj
    id: output_red
    min_power: 0.00095
    zero_means_zero: true
    channel: 2
  - platform: bp1658cj
    id: output_green
    min_power: 0.00095
    zero_means_zero: true
    channel: 1
  - platform: bp1658cj
    id: output_blue
    min_power: 0.00095
    zero_means_zero: true
    channel: 0
  - platform: bp1658cj
    id: output_cold_white
    min_power: 0.00095
    max_power: 0.9
    zero_means_zero: true
    channel: 3
  - platform: bp1658cj
    id: output_warm_white
    min_power: 0.00095
    max_power: 0.9
    zero_means_zero: true
    channel: 4

light:
  - platform: rgbww
    name:  Light
    id: light1
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6500.0 K
    warm_white_color_temperature: 2700.0 K 
    color_interlock: true
    constant_brightness: true
    restore_mode: RESTORE_AND_ON
    
captive_portal:
    
```
